# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75e905704268a7c6ace9926b8d08a5b1b6492620f34885afd0bee3dde8068283f60a1453aa81b5f2f26e9ae7ed6ddbceea228c9dfe9ef9787b129e88635ed8b0

test:
  secret_key_base: 88851f55adee5c0f8c4c42d4ac07e2c58e8b3122b6a0f9299b2f0ca4eb4ea2430c170eb474bbbd265e6d6b7c5972a4ad04a61984c784a7393e7af93636ba9f4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
